#######
# Cloudify Blueprint which describes a xap cluster (single node)
#
imports:
     -  http://www.getcloudify.org/spec/cloudify/3.0/types.yaml
     -  http://www.getcloudify.org/spec/bash-plugin/1.0/plugin.yaml
     -  http://www.getcloudify.org/spec/openstack-plugin/1.0/plugin.yaml

plugins:
    xap_config_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            folder: xap-config-plugin

    xap_admin_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            folder: xap-admin-plugin

    xap_workflow_plugin:
        derived_from: cloudify.plugins.manager_plugin
        properties:
            folder: xap-workflow-plugin

workflows:
    deploy_grid:
        mapping: xap_workflow_plugin.tasks.deploy_grid
        parameters:
            - grid_name: dataGrid
            - schema: partitioned-sync2backup
            - partitions: 1
            - backups: 0
            - max_per_vm: 0
            - max_per_machine: 0
    deploy_pu:
        mapping: xap_workflow_plugin.tasks.deploy_pu
        parameters:
            - pu_url: ""
            - override_pu_name: ""
            - schema: partitioned-sync2backup
            - partitions: 1
            - backups: 0
            - max_per_vm: 0
            - max_per_machine: 0
    undeploy_grid:
        mapping: xap_workflow_plugin.tasks.undeploy_grid
        parameters:
            - grid_name: dataGrid

types:
    vm_host:
        derived_from: cloudify.openstack.server
        properties:
            - cloudify_agent:
                user: ubuntu

    xap_type:
        derived_from: cloudify.types.bash.app_server
        properties:
            - GSA_JAVA_OPTS: ""
            - gsm_cnt: 0
            - global_gsm_cnt: 0
            - GSM_JAVA_OPTS: ""
            - lus_cnt: 0
            - lus_port: 0
            - lrmi_comm_min_port: 7122
            - lrmi_comm_max_port: 7222
            - LUS_JAVA_OPTS: ""
            - global_lus_cnt: 0
            - gsc_cnt: 0
            - GSC_JAVA_OPTS: ""
            - download_url: http://gigaspaces-repository-eu.s3.amazonaws.com/com/gigaspaces/xap-core/10.1.0-SNAPSHOT/gigaspaces-xap-premium-10.1.0-m4-b12584-514.zip
            - license_key: ""
            - scripts:
                create: xap-scripts/install-xap.sh
                start: xap-scripts/start-xap.sh
                stop: xap-scripts/stop-xap.sh

    demo_shell:
        derived_from: cloudify.types.bash.web_server
        properties:
            - butterfly_repo: https://github.com/CloudifySource/butterfly.git
            - demo_url: https://github.com/Gigaspaces/XAP-Interactive-Tutorial/archive/master.zip
            - port: 9099
            - lrmi_comm_min_port: 7122
            - lrmi_comm_max_port: 7222

relationships:
    xap_connected_to_lus:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                - postconfigure: xap_config_plugin.tasks.get_locator

blueprint:
    name: xap
    nodes:
        -   name: xap_mgmt_security_group
            type: cloudify.openstack.security_group
            properties:
                security_group:
                    name: xap_mgmt_security_group
                rules:
                    - remote_ip_prefix: 0.0.0.0/0
                      port: 8099
                    - remote_ip_prefix: 0.0.0.0/0
                      port: 9099
                    - remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7122
                      port_range_max: 7222
                    - direction: egress
                      remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7122
                      port_range_max: 7222
                    - remote_ip_prefix: 0.0.0.0/0
                      port: 4174
                    - direction: egress
                      remote_ip_prefix: 0.0.0.0/0
                      port: 4174
                    - remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7102
                      port_range_max: 7104
                    - direction: egress
                      remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7102
                      port_range_max: 7104

        -   name: xap_container_security_group
            type: cloudify.openstack.security_group
            properties:
                security_group:
                    name: xap_container_security_group
                rules:
                    - remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7122
                      port_range_max: 7222
                    - direction: egress
                      remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7122
                      port_range_max: 7222
                    - remote_ip_prefix: 0.0.0.0/0
                      port: 4174
                    - direction: egress
                      remote_ip_prefix: 0.0.0.0/0
                      port: 4174
                    - remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7102
                      port_range_max: 7104
                    - direction: egress
                      remote_ip_prefix: 0.0.0.0/0
                      port_range_min: 7102
                      port_range_max: 7104

        -   name: floatingip
            type: cloudify.openstack.floatingip
            properties:
                floatingip:
                    floating_network_name: Ext-Net

        -   name: xap_mgmt_vm
            type: vm_host
            instances:
                deploy: 1
            properties:
              server:
                  image: cec56e36-3c3a-4121-a6a1-6b7bef22d811
                  flavor: 102
                  security_groups: ['xap_mgmt_security_group']
            relationships:
                - target: floatingip
                  type: cloudify.openstack.server_connected_to_floating_ip
                - target: xap_mgmt_security_group
                  type: cloudify.relationships.depends_on

        -   name: xap_container_vm
            type: vm_host
            instances:
                deploy: 1
            properties:
              server:
                  image: cec56e36-3c3a-4121-a6a1-6b7bef22d811
                  flavor: 102
                  security_groups: ['xap_container_security_group']
            relationships:
                - target: xap_container_security_group
                  type: cloudify.relationships.depends_on

        -   name: xap_mgmt
            type: xap_type
            properties:
                lus_cnt: 1
                gsm_cnt: 1
                GSC_JAVA_OPTS: -Xms128m -Xmx128m
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
            interfaces:
                admin.commands:
                  -   deploy_grid:
                          mapping: xap_admin_plugin.tasks.deploy_grid
                          properties:
                              script: xap-scripts/deploy-grid.sh
                  -   undeploy_grid:
                          mapping: xap_admin_plugin.tasks.undeploy_grid
                          properties:
                              script: xap-scripts/undeploy-grid.sh
                  -   deploy_pu:
                          mapping: xap_admin_plugin.tasks.deploy_pu
                          properties:
                              script: xap-scripts/deploy-pu.sh

        -   name: interactive_shell
            type: demo_shell
            properties:
                scripts:
                    create: butterfly-scripts/install.sh
                    start:  butterfly-scripts/start.sh
                    stop:   butterfly-script/stop.sh
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: cloudify.relationships.depends_on

        -   name: webui
            type: cloudify.types.bash.web_server
            properties:
                scripts:
                    start: xap-scripts/start-ui.sh
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: cloudify.relationships.depends_on

        -   name: sample-space
            type: cloudify.types.bash.app_module
            properties:
                scripts:
                    start: xap-scripts/deploy-demo-grid.sh
            relationships:
                -   target: xap_mgmt_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: cloudify.relationships.depends_on

        -   name: xap_container
            type: xap_type
            properties:
                gsc_cnt: 1
                GSC_JAVA_OPTS: -Xms128m -Xmx128m
            relationships:
                -   target: xap_container_vm
                    type: cloudify.relationships.contained_in
                -   target: xap_mgmt
                    type: xap_connected_to_lus